//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference1
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetIndividualTrnResponse", Namespace="http://schemas.datacontract.org/2004/07/MLSS.Services.TRN.ServiceDataContracts")]
    public partial class GetIndividualTrnResponse : object
    {
        
        private ServiceReference1.IndividualTRN IndividualInfoField;
        
        private ServiceReference1.ServiceResponseStatus ResultStatusField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.IndividualTRN IndividualInfo
        {
            get
            {
                return this.IndividualInfoField;
            }
            set
            {
                this.IndividualInfoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.ServiceResponseStatus ResultStatus
        {
            get
            {
                return this.ResultStatusField;
            }
            set
            {
                this.ResultStatusField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IndividualTRN", Namespace="http://schemas.datacontract.org/2004/07/MLSS.Services.TRN.ServiceDataContracts")]
    public partial class IndividualTRN : object
    {
        
        private System.Nullable<System.DateTime> BirthDateField;
        
        private string BranchRefNbrField;
        
        private string FirstNameField;
        
        private string FlgStatusField;
        
        private string GenderTypeField;
        
        private string HmCountryCodeField;
        
        private string HmMarkTextField;
        
        private string HmParishCodeField;
        
        private string HmPoBoxNoField;
        
        private string HmPoLocNameField;
        
        private string HmStreetNameField;
        
        private string HmStreetNoField;
        
        private string LastNameField;
        
        private System.Nullable<System.DateTime> LastUpdateField;
        
        private string MiddleNameField;
        
        private string MlCountryCodeField;
        
        private string MlMarkTextField;
        
        private string MlParishCodeField;
        
        private string MlPoBoxNoField;
        
        private string MlPoLocNameField;
        
        private string MlStreetNameField;
        
        private string MlStreetNoField;
        
        private string NbrBranchField;
        
        private string NbrReferenceTrnField;
        
        private string NbrTrnField;
        
        private string TRNEntryStatusField;
        
        private System.Nullable<System.DateTime> TrnEntryDateField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> BirthDate
        {
            get
            {
                return this.BirthDateField;
            }
            set
            {
                this.BirthDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BranchRefNbr
        {
            get
            {
                return this.BranchRefNbrField;
            }
            set
            {
                this.BranchRefNbrField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName
        {
            get
            {
                return this.FirstNameField;
            }
            set
            {
                this.FirstNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FlgStatus
        {
            get
            {
                return this.FlgStatusField;
            }
            set
            {
                this.FlgStatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GenderType
        {
            get
            {
                return this.GenderTypeField;
            }
            set
            {
                this.GenderTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HmCountryCode
        {
            get
            {
                return this.HmCountryCodeField;
            }
            set
            {
                this.HmCountryCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HmMarkText
        {
            get
            {
                return this.HmMarkTextField;
            }
            set
            {
                this.HmMarkTextField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HmParishCode
        {
            get
            {
                return this.HmParishCodeField;
            }
            set
            {
                this.HmParishCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HmPoBoxNo
        {
            get
            {
                return this.HmPoBoxNoField;
            }
            set
            {
                this.HmPoBoxNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HmPoLocName
        {
            get
            {
                return this.HmPoLocNameField;
            }
            set
            {
                this.HmPoLocNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HmStreetName
        {
            get
            {
                return this.HmStreetNameField;
            }
            set
            {
                this.HmStreetNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HmStreetNo
        {
            get
            {
                return this.HmStreetNoField;
            }
            set
            {
                this.HmStreetNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName
        {
            get
            {
                return this.LastNameField;
            }
            set
            {
                this.LastNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> LastUpdate
        {
            get
            {
                return this.LastUpdateField;
            }
            set
            {
                this.LastUpdateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MiddleName
        {
            get
            {
                return this.MiddleNameField;
            }
            set
            {
                this.MiddleNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MlCountryCode
        {
            get
            {
                return this.MlCountryCodeField;
            }
            set
            {
                this.MlCountryCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MlMarkText
        {
            get
            {
                return this.MlMarkTextField;
            }
            set
            {
                this.MlMarkTextField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MlParishCode
        {
            get
            {
                return this.MlParishCodeField;
            }
            set
            {
                this.MlParishCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MlPoBoxNo
        {
            get
            {
                return this.MlPoBoxNoField;
            }
            set
            {
                this.MlPoBoxNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MlPoLocName
        {
            get
            {
                return this.MlPoLocNameField;
            }
            set
            {
                this.MlPoLocNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MlStreetName
        {
            get
            {
                return this.MlStreetNameField;
            }
            set
            {
                this.MlStreetNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MlStreetNo
        {
            get
            {
                return this.MlStreetNoField;
            }
            set
            {
                this.MlStreetNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NbrBranch
        {
            get
            {
                return this.NbrBranchField;
            }
            set
            {
                this.NbrBranchField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NbrReferenceTrn
        {
            get
            {
                return this.NbrReferenceTrnField;
            }
            set
            {
                this.NbrReferenceTrnField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NbrTrn
        {
            get
            {
                return this.NbrTrnField;
            }
            set
            {
                this.NbrTrnField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TRNEntryStatus
        {
            get
            {
                return this.TRNEntryStatusField;
            }
            set
            {
                this.TRNEntryStatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> TrnEntryDate
        {
            get
            {
                return this.TrnEntryDateField;
            }
            set
            {
                this.TrnEntryDateField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceResponseStatus", Namespace="http://schemas.datacontract.org/2004/07/MLSS.Services.Common.Entities")]
    public partial class ServiceResponseStatus : object
    {
        
        private string ErrorMessageField;
        
        private bool IsSuccessField;
        
        private string SuccessMessageField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string ErrorMessage
        {
            get
            {
                return this.ErrorMessageField;
            }
            set
            {
                this.ErrorMessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool IsSuccess
        {
            get
            {
                return this.IsSuccessField;
            }
            set
            {
                this.IsSuccessField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string SuccessMessage
        {
            get
            {
                return this.SuccessMessageField;
            }
            set
            {
                this.SuccessMessageField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MLSSFaultContract", Namespace="http://schemas.datacontract.org/2004/07/MLSS.Services.Common.Behaviours.Exception" +
        "Handling")]
    public partial class MLSSFaultContract : object
    {
        
        private System.Exception AdditionErrorDetailsField;
        
        private string ErrorDetailsField;
        
        private string ErrorMessageField;
        
        private bool ResultField;
        
        private string ServiceTypeField;
        
        private System.DateTime TimeStampField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Exception AdditionErrorDetails
        {
            get
            {
                return this.AdditionErrorDetailsField;
            }
            set
            {
                this.AdditionErrorDetailsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorDetails
        {
            get
            {
                return this.ErrorDetailsField;
            }
            set
            {
                this.ErrorDetailsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage
        {
            get
            {
                return this.ErrorMessageField;
            }
            set
            {
                this.ErrorMessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Result
        {
            get
            {
                return this.ResultField;
            }
            set
            {
                this.ResultField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ServiceType
        {
            get
            {
                return this.ServiceTypeField;
            }
            set
            {
                this.ServiceTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime TimeStamp
        {
            get
            {
                return this.TimeStampField;
            }
            set
            {
                this.TimeStampField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetIndividualTrnDetailsResponse", Namespace="http://schemas.datacontract.org/2004/07/MLSS.Services.TRN.ServiceDataContracts")]
    public partial class GetIndividualTrnDetailsResponse : object
    {
        
        private ServiceReference1.IndividualTRNDetails IndividualDetailsField;
        
        private ServiceReference1.ServiceResponseStatus ResultStatusField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.IndividualTRNDetails IndividualDetails
        {
            get
            {
                return this.IndividualDetailsField;
            }
            set
            {
                this.IndividualDetailsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.ServiceResponseStatus ResultStatus
        {
            get
            {
                return this.ResultStatusField;
            }
            set
            {
                this.ResultStatusField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IndividualTRNDetails", Namespace="http://schemas.datacontract.org/2004/07/MLSS.Services.TRN.ServiceDataContracts")]
    public partial class IndividualTRNDetails : object
    {
        
        private ServiceReference1.BusinessTRN[] BusinessesField;
        
        private ServiceReference1.IndividualTRN OIndividualDTOField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.BusinessTRN[] Businesses
        {
            get
            {
                return this.BusinessesField;
            }
            set
            {
                this.BusinessesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.IndividualTRN OIndividualDTO
        {
            get
            {
                return this.OIndividualDTOField;
            }
            set
            {
                this.OIndividualDTOField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BusinessTRN", Namespace="http://schemas.datacontract.org/2004/07/MLSS.Services.TRN.ServiceDataContracts")]
    public partial class BusinessTRN : object
    {
        
        private string BranchRefNbrField;
        
        private string BusinessNameField;
        
        private System.Nullable<System.DateTime> ClosedDateField;
        
        private string FlgStatusField;
        
        private string HmCountryCodeField;
        
        private string HmMarkTextField;
        
        private string HmParishCodeField;
        
        private string HmPoBoxNoField;
        
        private string HmPoLocNameField;
        
        private string HmStreetNameField;
        
        private string HmStreetNoField;
        
        private System.Nullable<System.DateTime> LastUpdateField;
        
        private string MlCountryCodeField;
        
        private string MlMarkTextField;
        
        private string MlParishCodeField;
        
        private string MlPoBoxNoField;
        
        private string MlPoLocNameField;
        
        private string MlStreetNameField;
        
        private string MlStreetNoField;
        
        private string NatureOfBusinessField;
        
        private string NbrBranchField;
        
        private string NbrReferenceTrnField;
        
        private string NbrTrnField;
        
        private string OrganTypeField;
        
        private System.Nullable<System.DateTime> RegnDateField;
        
        private System.Nullable<System.DateTime> StartDateField;
        
        private string TradeNameField;
        
        private System.Nullable<System.DateTime> TrnEntryDateField;
        
        private string TrnEntryStatusField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BranchRefNbr
        {
            get
            {
                return this.BranchRefNbrField;
            }
            set
            {
                this.BranchRefNbrField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BusinessName
        {
            get
            {
                return this.BusinessNameField;
            }
            set
            {
                this.BusinessNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ClosedDate
        {
            get
            {
                return this.ClosedDateField;
            }
            set
            {
                this.ClosedDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FlgStatus
        {
            get
            {
                return this.FlgStatusField;
            }
            set
            {
                this.FlgStatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HmCountryCode
        {
            get
            {
                return this.HmCountryCodeField;
            }
            set
            {
                this.HmCountryCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HmMarkText
        {
            get
            {
                return this.HmMarkTextField;
            }
            set
            {
                this.HmMarkTextField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HmParishCode
        {
            get
            {
                return this.HmParishCodeField;
            }
            set
            {
                this.HmParishCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HmPoBoxNo
        {
            get
            {
                return this.HmPoBoxNoField;
            }
            set
            {
                this.HmPoBoxNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HmPoLocName
        {
            get
            {
                return this.HmPoLocNameField;
            }
            set
            {
                this.HmPoLocNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HmStreetName
        {
            get
            {
                return this.HmStreetNameField;
            }
            set
            {
                this.HmStreetNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HmStreetNo
        {
            get
            {
                return this.HmStreetNoField;
            }
            set
            {
                this.HmStreetNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> LastUpdate
        {
            get
            {
                return this.LastUpdateField;
            }
            set
            {
                this.LastUpdateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MlCountryCode
        {
            get
            {
                return this.MlCountryCodeField;
            }
            set
            {
                this.MlCountryCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MlMarkText
        {
            get
            {
                return this.MlMarkTextField;
            }
            set
            {
                this.MlMarkTextField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MlParishCode
        {
            get
            {
                return this.MlParishCodeField;
            }
            set
            {
                this.MlParishCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MlPoBoxNo
        {
            get
            {
                return this.MlPoBoxNoField;
            }
            set
            {
                this.MlPoBoxNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MlPoLocName
        {
            get
            {
                return this.MlPoLocNameField;
            }
            set
            {
                this.MlPoLocNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MlStreetName
        {
            get
            {
                return this.MlStreetNameField;
            }
            set
            {
                this.MlStreetNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MlStreetNo
        {
            get
            {
                return this.MlStreetNoField;
            }
            set
            {
                this.MlStreetNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NatureOfBusiness
        {
            get
            {
                return this.NatureOfBusinessField;
            }
            set
            {
                this.NatureOfBusinessField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NbrBranch
        {
            get
            {
                return this.NbrBranchField;
            }
            set
            {
                this.NbrBranchField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NbrReferenceTrn
        {
            get
            {
                return this.NbrReferenceTrnField;
            }
            set
            {
                this.NbrReferenceTrnField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NbrTrn
        {
            get
            {
                return this.NbrTrnField;
            }
            set
            {
                this.NbrTrnField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrganType
        {
            get
            {
                return this.OrganTypeField;
            }
            set
            {
                this.OrganTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> RegnDate
        {
            get
            {
                return this.RegnDateField;
            }
            set
            {
                this.RegnDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> StartDate
        {
            get
            {
                return this.StartDateField;
            }
            set
            {
                this.StartDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TradeName
        {
            get
            {
                return this.TradeNameField;
            }
            set
            {
                this.TradeNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> TrnEntryDate
        {
            get
            {
                return this.TrnEntryDateField;
            }
            set
            {
                this.TrnEntryDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TrnEntryStatus
        {
            get
            {
                return this.TrnEntryStatusField;
            }
            set
            {
                this.TrnEntryStatusField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetTRNDataResponse", Namespace="http://schemas.datacontract.org/2004/07/MLSS.Services.TRN.ServiceDataContracts")]
    public partial class GetTRNDataResponse : object
    {
        
        private ServiceReference1.ServiceResponseStatus ResultStatusField;
        
        private ServiceReference1.TRNExtended TrnExtendedInfoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.ServiceResponseStatus ResultStatus
        {
            get
            {
                return this.ResultStatusField;
            }
            set
            {
                this.ResultStatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.TRNExtended TrnExtendedInfo
        {
            get
            {
                return this.TrnExtendedInfoField;
            }
            set
            {
                this.TrnExtendedInfoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TRNExtended", Namespace="http://schemas.datacontract.org/2004/07/MLSS.Services.TRN.ServiceDataContracts")]
    public partial class TRNExtended : object
    {
        
        private ServiceReference1.BusinessTRN BusinessInfoField;
        
        private ServiceReference1.IndividualTRNExtended IndividualExtInfoField;
        
        private ServiceReference1.IndividualTRN IndividualInfoField;
        
        private string NisRefNumberField;
        
        private ServiceReference1.TRN TrnInfoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.BusinessTRN BusinessInfo
        {
            get
            {
                return this.BusinessInfoField;
            }
            set
            {
                this.BusinessInfoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.IndividualTRNExtended IndividualExtInfo
        {
            get
            {
                return this.IndividualExtInfoField;
            }
            set
            {
                this.IndividualExtInfoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.IndividualTRN IndividualInfo
        {
            get
            {
                return this.IndividualInfoField;
            }
            set
            {
                this.IndividualInfoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NisRefNumber
        {
            get
            {
                return this.NisRefNumberField;
            }
            set
            {
                this.NisRefNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.TRN TrnInfo
        {
            get
            {
                return this.TrnInfoField;
            }
            set
            {
                this.TrnInfoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IndividualTRNExtended", Namespace="http://schemas.datacontract.org/2004/07/MLSS.Services.TRN.ServiceDataContracts")]
    public partial class IndividualTRNExtended : object
    {
        
        private string BirthCountryCodeField;
        
        private string BirthCountryNameField;
        
        private System.Nullable<System.DateTime> BirthDateField;
        
        private ServiceReference1.TaxpayerName CurrentNameField;
        
        private ServiceReference1.Employer EmployerInfoField;
        
        private string GenderField;
        
        private System.Nullable<System.DateTime> LastUpdateDtimeField;
        
        private ServiceReference1.Address MailingAddressField;
        
        private string MaritalStatusField;
        
        private string MaritalStatusDescField;
        
        private ServiceReference1.TaxpayerName NameAtBirthField;
        
        private string NameChangeCodeField;
        
        private string NameChangeDescField;
        
        private string NationalityCountryCodeField;
        
        private string NationalityCountryNameField;
        
        private string NatureOfBusinessCodeField;
        
        private string NatureOfBusinessDescField;
        
        private string OccupationCodeField;
        
        private string OccupationDescField;
        
        private string PlaceOfBirthField;
        
        private string ReferencedTRNField;
        
        private ServiceReference1.Address ResidentAddressField;
        
        private string SoleProprietorFlagField;
        
        private System.Nullable<System.DateTime> TrnAssignedDateField;
        
        private string TrnNbrField;
        
        private string TrnStatusField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BirthCountryCode
        {
            get
            {
                return this.BirthCountryCodeField;
            }
            set
            {
                this.BirthCountryCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BirthCountryName
        {
            get
            {
                return this.BirthCountryNameField;
            }
            set
            {
                this.BirthCountryNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> BirthDate
        {
            get
            {
                return this.BirthDateField;
            }
            set
            {
                this.BirthDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.TaxpayerName CurrentName
        {
            get
            {
                return this.CurrentNameField;
            }
            set
            {
                this.CurrentNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.Employer EmployerInfo
        {
            get
            {
                return this.EmployerInfoField;
            }
            set
            {
                this.EmployerInfoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Gender
        {
            get
            {
                return this.GenderField;
            }
            set
            {
                this.GenderField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> LastUpdateDtime
        {
            get
            {
                return this.LastUpdateDtimeField;
            }
            set
            {
                this.LastUpdateDtimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.Address MailingAddress
        {
            get
            {
                return this.MailingAddressField;
            }
            set
            {
                this.MailingAddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MaritalStatus
        {
            get
            {
                return this.MaritalStatusField;
            }
            set
            {
                this.MaritalStatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MaritalStatusDesc
        {
            get
            {
                return this.MaritalStatusDescField;
            }
            set
            {
                this.MaritalStatusDescField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.TaxpayerName NameAtBirth
        {
            get
            {
                return this.NameAtBirthField;
            }
            set
            {
                this.NameAtBirthField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NameChangeCode
        {
            get
            {
                return this.NameChangeCodeField;
            }
            set
            {
                this.NameChangeCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NameChangeDesc
        {
            get
            {
                return this.NameChangeDescField;
            }
            set
            {
                this.NameChangeDescField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NationalityCountryCode
        {
            get
            {
                return this.NationalityCountryCodeField;
            }
            set
            {
                this.NationalityCountryCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NationalityCountryName
        {
            get
            {
                return this.NationalityCountryNameField;
            }
            set
            {
                this.NationalityCountryNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NatureOfBusinessCode
        {
            get
            {
                return this.NatureOfBusinessCodeField;
            }
            set
            {
                this.NatureOfBusinessCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NatureOfBusinessDesc
        {
            get
            {
                return this.NatureOfBusinessDescField;
            }
            set
            {
                this.NatureOfBusinessDescField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OccupationCode
        {
            get
            {
                return this.OccupationCodeField;
            }
            set
            {
                this.OccupationCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OccupationDesc
        {
            get
            {
                return this.OccupationDescField;
            }
            set
            {
                this.OccupationDescField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PlaceOfBirth
        {
            get
            {
                return this.PlaceOfBirthField;
            }
            set
            {
                this.PlaceOfBirthField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReferencedTRN
        {
            get
            {
                return this.ReferencedTRNField;
            }
            set
            {
                this.ReferencedTRNField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.Address ResidentAddress
        {
            get
            {
                return this.ResidentAddressField;
            }
            set
            {
                this.ResidentAddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SoleProprietorFlag
        {
            get
            {
                return this.SoleProprietorFlagField;
            }
            set
            {
                this.SoleProprietorFlagField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> TrnAssignedDate
        {
            get
            {
                return this.TrnAssignedDateField;
            }
            set
            {
                this.TrnAssignedDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TrnNbr
        {
            get
            {
                return this.TrnNbrField;
            }
            set
            {
                this.TrnNbrField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TrnStatus
        {
            get
            {
                return this.TrnStatusField;
            }
            set
            {
                this.TrnStatusField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TRN", Namespace="http://schemas.datacontract.org/2004/07/MLSS.Services.TRN.ServiceDataContracts")]
    public partial class TRN : object
    {
        
        private string AddrCountryCodeField;
        
        private string AddrCountryDescField;
        
        private string AddrMarkTextField;
        
        private string AddrParishCodeField;
        
        private string AddrParishDescField;
        
        private string AddrPoBoxNoField;
        
        private string AddrPoLocNameField;
        
        private string AddrStreetNameField;
        
        private string AddrStreetNoField;
        
        private string AddressField;
        
        private System.Nullable<int> BadChequeIDField;
        
        private string BirthFirstNameField;
        
        private string BirthLastNameField;
        
        private string BirthMiddleNameField;
        
        private string BranchRefNbrField;
        
        private bool BusinessTrnField;
        
        private string FirstNameField;
        
        private string FlgStatusField;
        
        private string FlgTrnTypeField;
        
        private string FormattedNameField;
        
        private string GenderTypeField;
        
        private bool IndividualTrnField;
        
        private string LastNameField;
        
        private System.Nullable<System.DateTime> LastUpdateField;
        
        private string MaritalStatField;
        
        private string MiddleNameField;
        
        private string NbrBranchField;
        
        private string NbrReferenceTrnField;
        
        private string NbrTrnField;
        
        private System.Nullable<int> RegisteredField;
        
        private string RpdAlertField;
        
        private System.Nullable<int> TransIDField;
        
        private System.Nullable<System.DateTime> TrnEntryDateField;
        
        private string TrnEntryStatusField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AddrCountryCode
        {
            get
            {
                return this.AddrCountryCodeField;
            }
            set
            {
                this.AddrCountryCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AddrCountryDesc
        {
            get
            {
                return this.AddrCountryDescField;
            }
            set
            {
                this.AddrCountryDescField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AddrMarkText
        {
            get
            {
                return this.AddrMarkTextField;
            }
            set
            {
                this.AddrMarkTextField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AddrParishCode
        {
            get
            {
                return this.AddrParishCodeField;
            }
            set
            {
                this.AddrParishCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AddrParishDesc
        {
            get
            {
                return this.AddrParishDescField;
            }
            set
            {
                this.AddrParishDescField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AddrPoBoxNo
        {
            get
            {
                return this.AddrPoBoxNoField;
            }
            set
            {
                this.AddrPoBoxNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AddrPoLocName
        {
            get
            {
                return this.AddrPoLocNameField;
            }
            set
            {
                this.AddrPoLocNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AddrStreetName
        {
            get
            {
                return this.AddrStreetNameField;
            }
            set
            {
                this.AddrStreetNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AddrStreetNo
        {
            get
            {
                return this.AddrStreetNoField;
            }
            set
            {
                this.AddrStreetNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address
        {
            get
            {
                return this.AddressField;
            }
            set
            {
                this.AddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> BadChequeID
        {
            get
            {
                return this.BadChequeIDField;
            }
            set
            {
                this.BadChequeIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BirthFirstName
        {
            get
            {
                return this.BirthFirstNameField;
            }
            set
            {
                this.BirthFirstNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BirthLastName
        {
            get
            {
                return this.BirthLastNameField;
            }
            set
            {
                this.BirthLastNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BirthMiddleName
        {
            get
            {
                return this.BirthMiddleNameField;
            }
            set
            {
                this.BirthMiddleNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BranchRefNbr
        {
            get
            {
                return this.BranchRefNbrField;
            }
            set
            {
                this.BranchRefNbrField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BusinessTrn
        {
            get
            {
                return this.BusinessTrnField;
            }
            set
            {
                this.BusinessTrnField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName
        {
            get
            {
                return this.FirstNameField;
            }
            set
            {
                this.FirstNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FlgStatus
        {
            get
            {
                return this.FlgStatusField;
            }
            set
            {
                this.FlgStatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FlgTrnType
        {
            get
            {
                return this.FlgTrnTypeField;
            }
            set
            {
                this.FlgTrnTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FormattedName
        {
            get
            {
                return this.FormattedNameField;
            }
            set
            {
                this.FormattedNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GenderType
        {
            get
            {
                return this.GenderTypeField;
            }
            set
            {
                this.GenderTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IndividualTrn
        {
            get
            {
                return this.IndividualTrnField;
            }
            set
            {
                this.IndividualTrnField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName
        {
            get
            {
                return this.LastNameField;
            }
            set
            {
                this.LastNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> LastUpdate
        {
            get
            {
                return this.LastUpdateField;
            }
            set
            {
                this.LastUpdateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MaritalStat
        {
            get
            {
                return this.MaritalStatField;
            }
            set
            {
                this.MaritalStatField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MiddleName
        {
            get
            {
                return this.MiddleNameField;
            }
            set
            {
                this.MiddleNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NbrBranch
        {
            get
            {
                return this.NbrBranchField;
            }
            set
            {
                this.NbrBranchField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NbrReferenceTrn
        {
            get
            {
                return this.NbrReferenceTrnField;
            }
            set
            {
                this.NbrReferenceTrnField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NbrTrn
        {
            get
            {
                return this.NbrTrnField;
            }
            set
            {
                this.NbrTrnField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Registered
        {
            get
            {
                return this.RegisteredField;
            }
            set
            {
                this.RegisteredField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RpdAlert
        {
            get
            {
                return this.RpdAlertField;
            }
            set
            {
                this.RpdAlertField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> TransID
        {
            get
            {
                return this.TransIDField;
            }
            set
            {
                this.TransIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> TrnEntryDate
        {
            get
            {
                return this.TrnEntryDateField;
            }
            set
            {
                this.TrnEntryDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TrnEntryStatus
        {
            get
            {
                return this.TrnEntryStatusField;
            }
            set
            {
                this.TrnEntryStatusField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TaxpayerName", Namespace="http://schemas.datacontract.org/2004/07/MLSS.Services.TRN.ServiceDataContracts")]
    public partial class TaxpayerName : object
    {
        
        private string FirstNameField;
        
        private string LastNameField;
        
        private string MiddleNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName
        {
            get
            {
                return this.FirstNameField;
            }
            set
            {
                this.FirstNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName
        {
            get
            {
                return this.LastNameField;
            }
            set
            {
                this.LastNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MiddleName
        {
            get
            {
                return this.MiddleNameField;
            }
            set
            {
                this.MiddleNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Employer", Namespace="http://schemas.datacontract.org/2004/07/MLSS.Services.TRN.ServiceDataContracts")]
    public partial class Employer : object
    {
        
        private string EmployerAddressField;
        
        private string EmployerBranchNbrField;
        
        private string EmployerNameField;
        
        private string EmployerTRNField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmployerAddress
        {
            get
            {
                return this.EmployerAddressField;
            }
            set
            {
                this.EmployerAddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmployerBranchNbr
        {
            get
            {
                return this.EmployerBranchNbrField;
            }
            set
            {
                this.EmployerBranchNbrField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmployerName
        {
            get
            {
                return this.EmployerNameField;
            }
            set
            {
                this.EmployerNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmployerTRN
        {
            get
            {
                return this.EmployerTRNField;
            }
            set
            {
                this.EmployerTRNField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Address", Namespace="http://schemas.datacontract.org/2004/07/MLSS.Services.TRN.ServiceDataContracts")]
    public partial class Address : object
    {
        
        private string CountryCodeField;
        
        private string CountryNameField;
        
        private string MarkField;
        
        private string ParishCodeField;
        
        private string ParishNameField;
        
        private string PoBoxNumberField;
        
        private string PoLocationField;
        
        private string StreetNameField;
        
        private string StreetNumberField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CountryCode
        {
            get
            {
                return this.CountryCodeField;
            }
            set
            {
                this.CountryCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CountryName
        {
            get
            {
                return this.CountryNameField;
            }
            set
            {
                this.CountryNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mark
        {
            get
            {
                return this.MarkField;
            }
            set
            {
                this.MarkField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ParishCode
        {
            get
            {
                return this.ParishCodeField;
            }
            set
            {
                this.ParishCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ParishName
        {
            get
            {
                return this.ParishNameField;
            }
            set
            {
                this.ParishNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PoBoxNumber
        {
            get
            {
                return this.PoBoxNumberField;
            }
            set
            {
                this.PoBoxNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PoLocation
        {
            get
            {
                return this.PoLocationField;
            }
            set
            {
                this.PoLocationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StreetName
        {
            get
            {
                return this.StreetNameField;
            }
            set
            {
                this.StreetNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StreetNumber
        {
            get
            {
                return this.StreetNumberField;
            }
            set
            {
                this.StreetNumberField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ValidateTRNResponse", Namespace="http://schemas.datacontract.org/2004/07/MLSS.Services.TRN.ServiceDataContracts")]
    public partial class ValidateTRNResponse : object
    {
        
        private ServiceReference1.ServiceResponseStatus ResultStatusField;
        
        private ServiceReference1.TRN TrnInfoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.ServiceResponseStatus ResultStatus
        {
            get
            {
                return this.ResultStatusField;
            }
            set
            {
                this.ResultStatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.TRN TrnInfo
        {
            get
            {
                return this.TrnInfoField;
            }
            set
            {
                this.TrnInfoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetBusinessTrnResponse", Namespace="http://schemas.datacontract.org/2004/07/MLSS.Services.TRN.ServiceDataContracts")]
    public partial class GetBusinessTrnResponse : object
    {
        
        private ServiceReference1.BusinessTRN BusinessTrnField;
        
        private ServiceReference1.ServiceResponseStatus ResultStatusField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.BusinessTRN BusinessTrn
        {
            get
            {
                return this.BusinessTrnField;
            }
            set
            {
                this.BusinessTrnField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.ServiceResponseStatus ResultStatus
        {
            get
            {
                return this.ResultStatusField;
            }
            set
            {
                this.ResultStatusField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetBusinessTrnDetailsResponse", Namespace="http://schemas.datacontract.org/2004/07/MLSS.Services.TRN.ServiceDataContracts")]
    public partial class GetBusinessTrnDetailsResponse : object
    {
        
        private ServiceReference1.BusinessTRNDetails BusinessDetailsField;
        
        private ServiceReference1.ServiceResponseStatus ResultStatusField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.BusinessTRNDetails BusinessDetails
        {
            get
            {
                return this.BusinessDetailsField;
            }
            set
            {
                this.BusinessDetailsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.ServiceResponseStatus ResultStatus
        {
            get
            {
                return this.ResultStatusField;
            }
            set
            {
                this.ResultStatusField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BusinessTRNDetails", Namespace="http://schemas.datacontract.org/2004/07/MLSS.Services.TRN.ServiceDataContracts")]
    public partial class BusinessTRNDetails : object
    {
        
        private ServiceReference1.BusinessTRN[] BranchesField;
        
        private ServiceReference1.Owner[] OwnersField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.BusinessTRN[] Branches
        {
            get
            {
                return this.BranchesField;
            }
            set
            {
                this.BranchesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.Owner[] Owners
        {
            get
            {
                return this.OwnersField;
            }
            set
            {
                this.OwnersField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Owner", Namespace="http://schemas.datacontract.org/2004/07/MLSS.Services.TRN.ServiceDataContracts")]
    public partial class Owner : object
    {
        
        private string FirstNameField;
        
        private string LastNameField;
        
        private string MiddleNameField;
        
        private string NbrBranchField;
        
        private string NbrTrnField;
        
        private string TitleField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName
        {
            get
            {
                return this.FirstNameField;
            }
            set
            {
                this.FirstNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName
        {
            get
            {
                return this.LastNameField;
            }
            set
            {
                this.LastNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MiddleName
        {
            get
            {
                return this.MiddleNameField;
            }
            set
            {
                this.MiddleNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NbrBranch
        {
            get
            {
                return this.NbrBranchField;
            }
            set
            {
                this.NbrBranchField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NbrTrn
        {
            get
            {
                return this.NbrTrnField;
            }
            set
            {
                this.NbrTrnField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title
        {
            get
            {
                return this.TitleField;
            }
            set
            {
                this.TitleField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ValidateProvisionalTrnResponse", Namespace="http://schemas.datacontract.org/2004/07/MLSS.Services.TRN.ServiceDataContracts")]
    public partial class ValidateProvisionalTrnResponse : object
    {
        
        private ServiceReference1.ServiceResponseStatus ResultStatusField;
        
        private ServiceReference1.TRNExtended TrnExtendedInfoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.ServiceResponseStatus ResultStatus
        {
            get
            {
                return this.ResultStatusField;
            }
            set
            {
                this.ResultStatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.TRNExtended TrnExtendedInfo
        {
            get
            {
                return this.TrnExtendedInfoField;
            }
            set
            {
                this.TrnExtendedInfoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetIndividualTrnExtendedResponse", Namespace="http://schemas.datacontract.org/2004/07/MLSS.Services.TRN.ServiceDataContracts")]
    public partial class GetIndividualTrnExtendedResponse : object
    {
        
        private ServiceReference1.IndividualTRNExtended IndividualExtendedInfoField;
        
        private ServiceReference1.ServiceResponseStatus ResultStatusField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.IndividualTRNExtended IndividualExtendedInfo
        {
            get
            {
                return this.IndividualExtendedInfoField;
            }
            set
            {
                this.IndividualExtendedInfoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.ServiceResponseStatus ResultStatus
        {
            get
            {
                return this.ResultStatusField;
            }
            set
            {
                this.ResultStatusField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.ServiceContractAttribute(Name="MLSS.Services.TRN", Namespace="MLSS.Services.TRN", ConfigurationName="ServiceReference1.MLSSServicesTRN")]
    public interface MLSSServicesTRN
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="MLSS.Services.TRN/MLSS.Services.TRN/GetIndividualTrn", ReplyAction="MLSS.Services.TRN/MLSS.Services.TRN/GetIndividualTrnResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference1.MLSSFaultContract), Action="MLSS.Services.TRN/MLSS.Services.TRN/GetIndividualTrnMLSSFaultContractFault", Name="MLSSFaultContract", Namespace="http://schemas.datacontract.org/2004/07/MLSS.Services.Common.Behaviours.Exception" +
            "Handling")]
        ServiceReference1.GetIndividualTrnResponse GetIndividualTrn(int trnNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="MLSS.Services.TRN/MLSS.Services.TRN/GetIndividualTrn", ReplyAction="MLSS.Services.TRN/MLSS.Services.TRN/GetIndividualTrnResponse")]
        System.Threading.Tasks.Task<ServiceReference1.GetIndividualTrnResponse> GetIndividualTrnAsync(int trnNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="MLSS.Services.TRN/MLSS.Services.TRN/GetIndividualTrnDetails", ReplyAction="MLSS.Services.TRN/MLSS.Services.TRN/GetIndividualTrnDetailsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference1.MLSSFaultContract), Action="MLSS.Services.TRN/MLSS.Services.TRN/GetIndividualTrnDetailsMLSSFaultContractFault" +
            "", Name="MLSSFaultContract", Namespace="http://schemas.datacontract.org/2004/07/MLSS.Services.Common.Behaviours.Exception" +
            "Handling")]
        ServiceReference1.GetIndividualTrnDetailsResponse GetIndividualTrnDetails(int trnNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="MLSS.Services.TRN/MLSS.Services.TRN/GetIndividualTrnDetails", ReplyAction="MLSS.Services.TRN/MLSS.Services.TRN/GetIndividualTrnDetailsResponse")]
        System.Threading.Tasks.Task<ServiceReference1.GetIndividualTrnDetailsResponse> GetIndividualTrnDetailsAsync(int trnNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="MLSS.Services.TRN/MLSS.Services.TRN/GetTrnData", ReplyAction="MLSS.Services.TRN/MLSS.Services.TRN/GetTrnDataResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference1.MLSSFaultContract), Action="MLSS.Services.TRN/MLSS.Services.TRN/GetTrnDataMLSSFaultContractFault", Name="MLSSFaultContract", Namespace="http://schemas.datacontract.org/2004/07/MLSS.Services.Common.Behaviours.Exception" +
            "Handling")]
        ServiceReference1.GetTRNDataResponse GetTrnData(int trnNumber, short branchNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="MLSS.Services.TRN/MLSS.Services.TRN/GetTrnData", ReplyAction="MLSS.Services.TRN/MLSS.Services.TRN/GetTrnDataResponse")]
        System.Threading.Tasks.Task<ServiceReference1.GetTRNDataResponse> GetTrnDataAsync(int trnNumber, short branchNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="MLSS.Services.TRN/MLSS.Services.TRN/ValidateTrn", ReplyAction="MLSS.Services.TRN/MLSS.Services.TRN/ValidateTrnResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference1.MLSSFaultContract), Action="MLSS.Services.TRN/MLSS.Services.TRN/ValidateTrnMLSSFaultContractFault", Name="MLSSFaultContract", Namespace="http://schemas.datacontract.org/2004/07/MLSS.Services.Common.Behaviours.Exception" +
            "Handling")]
        ServiceReference1.ValidateTRNResponse ValidateTrn(int trnNumber, short branchNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="MLSS.Services.TRN/MLSS.Services.TRN/ValidateTrn", ReplyAction="MLSS.Services.TRN/MLSS.Services.TRN/ValidateTrnResponse")]
        System.Threading.Tasks.Task<ServiceReference1.ValidateTRNResponse> ValidateTrnAsync(int trnNumber, short branchNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="MLSS.Services.TRN/MLSS.Services.TRN/GetBusinessTrn", ReplyAction="MLSS.Services.TRN/MLSS.Services.TRN/GetBusinessTrnResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference1.MLSSFaultContract), Action="MLSS.Services.TRN/MLSS.Services.TRN/GetBusinessTrnMLSSFaultContractFault", Name="MLSSFaultContract", Namespace="http://schemas.datacontract.org/2004/07/MLSS.Services.Common.Behaviours.Exception" +
            "Handling")]
        ServiceReference1.GetBusinessTrnResponse GetBusinessTrn(int trnNumber, short branchNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="MLSS.Services.TRN/MLSS.Services.TRN/GetBusinessTrn", ReplyAction="MLSS.Services.TRN/MLSS.Services.TRN/GetBusinessTrnResponse")]
        System.Threading.Tasks.Task<ServiceReference1.GetBusinessTrnResponse> GetBusinessTrnAsync(int trnNumber, short branchNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="MLSS.Services.TRN/MLSS.Services.TRN/GetBusinessTrnDetails", ReplyAction="MLSS.Services.TRN/MLSS.Services.TRN/GetBusinessTrnDetailsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference1.MLSSFaultContract), Action="MLSS.Services.TRN/MLSS.Services.TRN/GetBusinessTrnDetailsMLSSFaultContractFault", Name="MLSSFaultContract", Namespace="http://schemas.datacontract.org/2004/07/MLSS.Services.Common.Behaviours.Exception" +
            "Handling")]
        ServiceReference1.GetBusinessTrnDetailsResponse GetBusinessTrnDetails(int trnNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="MLSS.Services.TRN/MLSS.Services.TRN/GetBusinessTrnDetails", ReplyAction="MLSS.Services.TRN/MLSS.Services.TRN/GetBusinessTrnDetailsResponse")]
        System.Threading.Tasks.Task<ServiceReference1.GetBusinessTrnDetailsResponse> GetBusinessTrnDetailsAsync(int trnNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="MLSS.Services.TRN/MLSS.Services.TRN/ValidateProvisionalTrn", ReplyAction="MLSS.Services.TRN/MLSS.Services.TRN/ValidateProvisionalTrnResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference1.MLSSFaultContract), Action="MLSS.Services.TRN/MLSS.Services.TRN/ValidateProvisionalTrnMLSSFaultContractFault", Name="MLSSFaultContract", Namespace="http://schemas.datacontract.org/2004/07/MLSS.Services.Common.Behaviours.Exception" +
            "Handling")]
        ServiceReference1.ValidateProvisionalTrnResponse ValidateProvisionalTrn(int trnNumber, short branchNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="MLSS.Services.TRN/MLSS.Services.TRN/ValidateProvisionalTrn", ReplyAction="MLSS.Services.TRN/MLSS.Services.TRN/ValidateProvisionalTrnResponse")]
        System.Threading.Tasks.Task<ServiceReference1.ValidateProvisionalTrnResponse> ValidateProvisionalTrnAsync(int trnNumber, short branchNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="MLSS.Services.TRN/MLSS.Services.TRN/GetIndividualTrnExtended", ReplyAction="MLSS.Services.TRN/MLSS.Services.TRN/GetIndividualTrnExtendedResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference1.MLSSFaultContract), Action="MLSS.Services.TRN/MLSS.Services.TRN/GetIndividualTrnExtendedMLSSFaultContractFaul" +
            "t", Name="MLSSFaultContract", Namespace="http://schemas.datacontract.org/2004/07/MLSS.Services.Common.Behaviours.Exception" +
            "Handling")]
        ServiceReference1.GetIndividualTrnExtendedResponse GetIndividualTrnExtended(string trnNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="MLSS.Services.TRN/MLSS.Services.TRN/GetIndividualTrnExtended", ReplyAction="MLSS.Services.TRN/MLSS.Services.TRN/GetIndividualTrnExtendedResponse")]
        System.Threading.Tasks.Task<ServiceReference1.GetIndividualTrnExtendedResponse> GetIndividualTrnExtendedAsync(string trnNumber);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    public interface MLSSServicesTRNChannel : ServiceReference1.MLSSServicesTRN, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    public partial class MLSSServicesTRNClient : System.ServiceModel.ClientBase<ServiceReference1.MLSSServicesTRN>, ServiceReference1.MLSSServicesTRN
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public MLSSServicesTRNClient() : 
                base(MLSSServicesTRNClient.GetDefaultBinding(), MLSSServicesTRNClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.TRNServiceEndPoint.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MLSSServicesTRNClient(EndpointConfiguration endpointConfiguration) : 
                base(MLSSServicesTRNClient.GetBindingForEndpoint(endpointConfiguration), MLSSServicesTRNClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MLSSServicesTRNClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(MLSSServicesTRNClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MLSSServicesTRNClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(MLSSServicesTRNClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MLSSServicesTRNClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public ServiceReference1.GetIndividualTrnResponse GetIndividualTrn(int trnNumber)
        {
            return base.Channel.GetIndividualTrn(trnNumber);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.GetIndividualTrnResponse> GetIndividualTrnAsync(int trnNumber)
        {
            return base.Channel.GetIndividualTrnAsync(trnNumber);
        }
        
        public ServiceReference1.GetIndividualTrnDetailsResponse GetIndividualTrnDetails(int trnNumber)
        {
            return base.Channel.GetIndividualTrnDetails(trnNumber);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.GetIndividualTrnDetailsResponse> GetIndividualTrnDetailsAsync(int trnNumber)
        {
            return base.Channel.GetIndividualTrnDetailsAsync(trnNumber);
        }
        
        public ServiceReference1.GetTRNDataResponse GetTrnData(int trnNumber, short branchNumber)
        {
            return base.Channel.GetTrnData(trnNumber, branchNumber);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.GetTRNDataResponse> GetTrnDataAsync(int trnNumber, short branchNumber)
        {
            return base.Channel.GetTrnDataAsync(trnNumber, branchNumber);
        }
        
        public ServiceReference1.ValidateTRNResponse ValidateTrn(int trnNumber, short branchNumber)
        {
            return base.Channel.ValidateTrn(trnNumber, branchNumber);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.ValidateTRNResponse> ValidateTrnAsync(int trnNumber, short branchNumber)
        {
            return base.Channel.ValidateTrnAsync(trnNumber, branchNumber);
        }
        
        public ServiceReference1.GetBusinessTrnResponse GetBusinessTrn(int trnNumber, short branchNumber)
        {
            return base.Channel.GetBusinessTrn(trnNumber, branchNumber);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.GetBusinessTrnResponse> GetBusinessTrnAsync(int trnNumber, short branchNumber)
        {
            return base.Channel.GetBusinessTrnAsync(trnNumber, branchNumber);
        }
        
        public ServiceReference1.GetBusinessTrnDetailsResponse GetBusinessTrnDetails(int trnNumber)
        {
            return base.Channel.GetBusinessTrnDetails(trnNumber);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.GetBusinessTrnDetailsResponse> GetBusinessTrnDetailsAsync(int trnNumber)
        {
            return base.Channel.GetBusinessTrnDetailsAsync(trnNumber);
        }
        
        public ServiceReference1.ValidateProvisionalTrnResponse ValidateProvisionalTrn(int trnNumber, short branchNumber)
        {
            return base.Channel.ValidateProvisionalTrn(trnNumber, branchNumber);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.ValidateProvisionalTrnResponse> ValidateProvisionalTrnAsync(int trnNumber, short branchNumber)
        {
            return base.Channel.ValidateProvisionalTrnAsync(trnNumber, branchNumber);
        }
        
        public ServiceReference1.GetIndividualTrnExtendedResponse GetIndividualTrnExtended(string trnNumber)
        {
            return base.Channel.GetIndividualTrnExtended(trnNumber);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.GetIndividualTrnExtendedResponse> GetIndividualTrnExtendedAsync(string trnNumber)
        {
            return base.Channel.GetIndividualTrnExtendedAsync(trnNumber);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.TRNServiceEndPoint))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.TRNServiceEndPoint))
            {
                return new System.ServiceModel.EndpointAddress(new System.Uri("http://jniss-app:84/TRN/ServiceOperations/TRNService.svc"), new System.ServiceModel.DnsEndpointIdentity("localhost"));
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return MLSSServicesTRNClient.GetBindingForEndpoint(EndpointConfiguration.TRNServiceEndPoint);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return MLSSServicesTRNClient.GetEndpointAddress(EndpointConfiguration.TRNServiceEndPoint);
        }
        
        public enum EndpointConfiguration
        {
            
            TRNServiceEndPoint,
        }
    }
}
